version: "1"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    container_name: jaeger
    ports:
      - "6831:6831/udp" # accepts jaeger.thrift over compact thrift protocol
      - "16686:16686" # ui
